spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/upgrade_scheduler
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver